import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import MainLayout from "@/components/layout/main-layout";
import "@/app/globals.css";

const nunito = Nunito_Sans({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800"],
	variable: "--font-nunito",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="vi">
			<body className={`${nunito.variable} text-dark font-sans antialiased`}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
