import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import "@/app/globals.css";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import { NextIntlClientProvider } from "next-intl";

const fontHeading = Outfit({
	variable: "--font-heading",
	// @ts-expect-error - 'vietnamese' subset is supported by Outfit but might not be in the types
	subsets: ["latin", "vietnamese"],
	weight: ["400", "500", "600", "700", "800"],
});

const fontSans = Inter({
	variable: "--font-sans",
	subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import FloatingContact from "@/components/layout/FloatingContact";

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!routing.locales.includes(locale as any)) notFound();

	let messages;
	try {
		const common = (await import(`@/messages/${locale}/common.json`)).default;
		const home = (await import(`@/messages/${locale}/home.json`)).default;
		// const navbar = (await import(`@/messages/${locale}/navbar.json`)).default;

		messages = {
			...common,
			...home,
			// ...navbar,
		};
	} catch (error) {
		console.error(error);
		notFound();
	}
	return (
		<html lang={locale}>
			<body className={`${fontSans.variable} ${fontHeading.variable} text-dark font-sans antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<div className="flex min-h-screen flex-col">
						<Header />
						<main className="grow">{children}</main>
						<Footer />
						<FloatingContact />
					</div>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
